packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
allowBuilds:
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
minimumReleaseAgeExclude:
  - electron@43.0.0
