export const companionChannels = {
  checkForUpdates: "companion:check-for-updates",
  copyBridgeUrl: "companion:copy-bridge-url",
  createPrinter: "companion:create-printer",
  createStream: "companion:create-stream",
  deletePrinter: "companion:delete-printer",
  deleteStream: "companion:delete-stream",
  discoverPrinters: "companion:discover-printers",
  exportDiagnostics: "companion:export-diagnostics",
  fileHandoff: "companion:file-handoff",
  getSnapshot: "companion:get-snapshot",
  openLogFolder: "companion:open-log-folder",
  openExternal: "companion:open-external",
  openUpdateDownload: "companion:open-update-download",
  pair: "companion:pair",
  readTelemetry: "companion:read-telemetry",
  regenerateBridgeToken: "companion:regenerate-bridge-token",
  rendererLog: "companion:renderer-log",
  resetPairing: "companion:reset-pairing",
  saveSettings: "companion:save-settings",
  testPrinter: "companion:test-printer",
  updatePrinter: "companion:update-printer",
  updateStream: "companion:update-stream",
} as const;
